CREATE TABLE TFORNECEDOR (
  FORCOD INTEGER NOT NULL,
  FORNOME VARCHAR(50) NOT NULL,
  FORENDERECO INTEGER NOT NULL,
  FORDESCRICAO VARCHAR(50),
  FORTELEFONE VARCHAR(15),
  FOREMAIL VARCHAR(50),
  CONSTRAINT PK_FORCOD PRIMARY KEY (FORCOD),
  CONSTRAINT FK_FORENDERECO FOREIGN KEY (FORENDERECO) REFERENCES TENDERECO(ENDCOD);   
);

CREATE TABLE TCLINTE (
  CLICOD INTEGER NOT NULL,
  CLINOME VARCHAR(50) NOT NULL,
  CLIENDERECO INTEGER NOT NULL,
  CLITELEFONE VARCHAR(15), 
  CLIEMAIL VARCHAR(50),
  CLICARTAOCREDITO INTEGER,
  CONSTRAINT PK_CLICOD PRIMARY KEY (CLICOD),
  CONSTRAINT FK_CLIENDERECO FOREIGN KEY (CLIENDERECO) REFERENCES TENDERECO(ENDCOD);  
)

CREATE TABLE TENDERECO (
  ENDCOD INTEGER NOT NULL,
  ENDREFERENCIA INTEGER NOT NULL,
  ENDRUA VARCHAR(100) NOT NULL,
  ENDNUMERO INTEGER NOT NULL,
  ENDCOMPLEMENTO VARCHAR(50),
  ENDBAIRRO VARCHAR(20),
  ENDCEP VARCHAR(9),
  ENDCIDADE VARCHAR(30), 
  ENDESTADO VARCHAR(30),
  CONSTRAINT PK_ENDCOD PRIMARY KEY(ENDCOD),
  CONSTRAINT FK_ENDCLIENTE FOREIGN KEY (ENDREFERENCIA) REFERENCES TCLIENTE(CLICOD),
  CONSTRAINT FK_ENDFORNECEDOR FOREIGN KEY (ENDREFERENCIA) REFERENCES TFORNECEDOR(FORCOD);
)

CREATE TABLE TPRODUTO (
  PROCOD INTEGER NOT NULL,
  PROESTOQUE INTEGER NOT NULL,
  PROFORNECEDOR INTEGER NOT NULL,
  PRONOME VARCHAR(50) NOT NULL,
  PRODESCRICAO VARCHAR(300) NOT NULL,
  PROFOTO
  CONSTRAINT PK_PROCOD PRIMARY KEY (PROCOD);
  CONSTRAINT FK_PROESTOQUE FOREIGN KEY (PROESTOQUE) REFERENCES TESTOQUE(ESTCOD),
  CONSTRAINT FK_PROFORNECEDOR FOREIGN KEY (PROFORNECEDOR) REFERENCES TFORNECEDOR(FORCOD);
)

CREATE TABLE TESTOQUE (
  ESTCOD INTEGER NOT NULL,
  ESTQUANTIDADE INTEGER NOT NULL,
  ESTPRECO FLOAT NOT NULL,
  CONSTRAINT PK_ESTCOD PRIMARY KEY (ESTCOD);
)

CREATE TABLE TPEDIDO (
  PEDNUMERO INTEGER NOT NULL,
  PEDCLIENTE INTEGER NOT NULL,
  PEDDATAPEDIDO DATE NOT NULL,
  PEDDATAENTREGA DATE NOT NULL,
  PEDSITUACAO VARCHAR(15) NOT NULL,
  CONSTRAINT PK_PEDNUMERO PRIMARY KEY (PEDNUMERO),
  CONSTRAINT FK_PEDCLIENTE FOREIGN KEY (PEDCLIENTE) REFERENCES TCLIENTE(CLICOD);
)
